scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: robot_body_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.31
        min_x: -0.31
        max_y: 0.23
        min_y: -0.23
        max_z: 1.0
        min_z: -0.5
        invert: false